name: tools
services:
  # NextExlorer
  nextexplorer:
    image: nxzai/explorer:latest
    container_name: nextexplorer
    restart: unless-stopped
    ports:
      - 11000:3000
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=https://nextexplorer.herbatka-test.duckdns.org
      - UID=${PUID}
      - GID=${PGID}
    volumes:
      - ${DOCKER_DIR}/nextexplorer/config:/config
      - ${DOCKER_DIR}/nextexplorer/cache:/cache
      - ${HOME_DIR}:/mnt/Home
      - ${HDD_DIR}:/mnt/HDD

  # Termix
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    restart: unless-stopped
    ports:
      - 11001:8080
    volumes:
      - termix-data:/app/data
    environment:
      - PORT=8080
      - PUID=${PUID}
      - PGID=${PGID}

  # IT Tools
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    hostname: it-tools
    ports:
      - 11002:80

  # PDF Tools
  bentopdf:
    image: bentopdf/bentopdf-simple:latest
    container_name: bentopdf
    ports:
      - 11003:8080
    restart: unless-stopped

  # Diagram tools
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    ports:
      - 11004:80
    restart: unless-stopped

  # DumbPad notes
  dumbpad:
    image: dumbwareio/dumbpad:latest
    container_name: dumbpad
    restart: unless-stopped
    ports:
      - 11005:3000
    volumes:
      - ${DOCKER_DIR}/dumbpad/data:/app/data
    environment:
      SITE_TITLE: ${DUMBPAD_SITE_TITLE}
      DUMBPAD_PIN: ${DUMBPAD_PIN}
      BASE_URL: ${DUMBPAD_BASE_URL}

volumes:
  termix-data:
    driver: local
